agents:
  taskmaster:
    enabled: true
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 1000
  
  task_agent:
    model: "gpt-4"
    temperature: 0.3
    max_steps: 10
    max_tokens: 2000
  
  subtask_agent:
    model: "gpt-4"
    temperature: 0.1
    max_subtasks: 20
    max_tokens: 3000
  
  executor:
    max_retries_per_command: 2
    auto_correction_enabled: true
    dry_run_mode: false
    command_timeout: 30
  
  error_handler:
    error_threshold_per_step: 4
    send_to_planner_after_threshold: true
    human_escalation_threshold: 3
    max_error_reports: 10

llm:
  api_key: "test-api-key-for-demo"
  base_url: "https://api.openai.com/v1"
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7
  timeout: 60

logging:
  level: "INFO"
  log_file: "logs/agent.log"
  error_file: "logs/errors.log"
  max_file_size: "10 MB"
  retention_days: 7
  compression: true

security:
  validate_commands: true
  log_forbidden_attempts: true
  require_confirmation_for_dangerous: true
  allowed_commands_only: false